export { default as Introduction } from "./introduction";
export { default as HomePage } from "./home-page";
export { default as About } from "./about";
export { default as Webcam1 } from "./webcam-1";
export { default as InsertCategories } from "./insert-categories";
export { default as Lesson } from "./lesson";
export { default as Quiz } from "./quiz";
export { default as GetStarted } from "./get-started";
export { default as AddToy } from "./add-toy";
